import type { Author } from "./types";

/* Titles, standfirsts, categories, bylines and dates exactly as the live
   gryd.energy listings publish them. Generated by docs/migrate-cards.mjs.
   Do not hand edit, regenerate instead. */

export type Card = {
  /** The article title, verbatim. */
  title: string;
  /** The standfirst shown on the listing card, verbatim. */
  dek: string;
  /** The live category label. Null on the three case studies, which the
      Projects listing files under no category. */
  category: string | null;
  author: string;
  date: string;
  /** Set where the live listing itself cuts the standfirst off mid sentence. */
  truncated: boolean;
  metaDescription: string | null;
};

export const cards: Record<string, Card> = {
  "council-housing-solar-index-2026": {
    "title": "Gryd’s Council Housing Solar Rankings 2026: Which Regions Are Leading and Which Are Falling Behind?",
    "dek": "Gryd has launched the Gryd Council Housing Solar Index, a new industry benchmark of council solar deployment across the UK. Discover which regions are leading and lagging behind.",
    "category": "Social housing",
    "author": "Danielle Todd",
    "date": "July 13, 2026",
    "truncated": false,
    "metaDescription": "Gryd has launched the Gryd Council Housing Solar Index, a new industry benchmark of council solar deployment across the UK. Discover which regions are leading and lagging behind."
  },
  "why-solar-farms-keep-getting-rejected": {
    "title": "Solar has never been more popular. So why do solar farms keep getting rejected?",
    "dek": "Solar enjoys 86% public support in the UK, yet the proposed Lime Down farm in Wiltshire drew nearly 5,000 objections. The same 500MW could sit on around 100,000 rooftops instead, generating power where people use it: no lost farmland, less grid congestion, lower bills from day one. There is another way to build 500MW, and it starts on the roof.",
    "category": "Solar",
    "author": "Scott Whiteside",
    "date": "June 25, 2026",
    "truncated": false,
    "metaDescription": "Solar farms face thousands of objections despite 86% public support. Distributed rooftop solar on new-build homes is a better way to deploy 500MW."
  },
  "complete-guide-to-funded-solar": {
    "title": "The Complete Guide to Funded Solar and Storage for New-Build Homes (2026)",
    "dek": "The Future Homes Standard makes solar unavoidable for new-build homes. This guide compares every route available to UK house builders for delivering solar and battery systems, from zero-CAPEX subscriptions and private-wire microgrids to energy supplier tariff partnerships, government schemes, and self-funding. Find the right model for your development.",
    "category": "Funding",
    "author": "Scott Whiteside",
    "date": "May 5, 2026",
    "truncated": false,
    "metaDescription": "Every funded solar and storage option for UK house builders compared. Zero-CAPEX subscriptions, microgrids, government grants, and more. Free site assessment."
  },
  "sap-scores-versus-real-energy-use": {
    "title": "SAP Scores vs Real Energy Use: Why Developers Are Missing Half the Picture",
    "dek": "SAP scores don’t account for total energy use in new homes. Learn why UK housebuilders must consider real demand and how solar can better support it.",
    "category": "Home Design",
    "author": "Hugo Radford",
    "date": "April 22, 2026",
    "truncated": false,
    "metaDescription": "SAP scores don’t account for total energy use in new homes. Learn why UK housebuilders must consider real demand and how solar can better support it."
  },
  "future-homes-standard-differentiate": {
    "title": "The Future Homes Standard: How to Differentiate When Everyone Must Comply",
    "dek": "The Future Homes Standard means every new home in England must include on-site renewable generation and low-carbon heating, from 2028. When compliance is universal, the question for developers shifts from whether to build sustainably to how to stand out.",
    "category": "FHS",
    "author": "Danielle Todd",
    "date": "March 25, 2026",
    "truncated": false,
    "metaDescription": "The Future Homes Standard means every new home in England must include on-site renewable generation and low-carbon heating, from 2028. When compliance is universal, the question for developers shifts from whether to build sustainably to how to stand out."
  },
  "how-much-solar-do-you-need": {
    "title": "Future Homes Standard: How to Calculate How Much Solar You Need",
    "dek": "On-site renewables is now a functional requirement for every new home in England. This guide breaks down the confirmed sizing formula from Approved Document L 2026 and explains why designing beyond the minimum is essential.",
    "category": "FHS",
    "author": "Scott Whiteside",
    "date": "March 24, 2026",
    "truncated": false,
    "metaDescription": "On-site renewables is now a functional requirement for every new home in England. This guide breaks down the confirmed sizing formula from Approved Document L 2026 and explains why designing beyond the minimum is essential."
  },
  "future-homes-standard-timeline": {
    "title": "The Future Homes Standard is Published — Here’s the Confirmed Timeline for Implementation",
    "dek": "The Future Homes Standard comes into force on 24 March 2027, with a 12-month transition deadline of 24 March 2028. Here is a practical breakdown of the confirmed implementation timeline, the HEM/SAP crossover, and what developers should be doing right now.",
    "category": "FHS",
    "author": "Scott Whiteside",
    "date": "March 24, 2026",
    "truncated": false,
    "metaDescription": "The Future Homes Standard comes into force on 24 March 2027, with a 12-month transition deadline of 24 March 2028. Here is a practical breakdown of the confirmed implementation timeline, the HEM/SAP crossover, and what developers should be doing right now."
  },
  "future-homes-standard-solar-mandate": {
    "title": "Future Homes Standard: What It Means For UK Housebuilders – And A Closer Look At The Solar Mandate",
    "dek": "Future Homes Standard explained for UK housebuilders. Learn how solar panels, heat pumps and battery storage will shape new build homes – and how to prepare for 2027 requirements.",
    "category": "FHS",
    "author": "Scott Whiteside",
    "date": "March 19, 2026",
    "truncated": false,
    "metaDescription": "Future Homes Standard explained for UK housebuilders. Learn how solar panels, heat pumps and battery storage will shape new build homes - and how to prepare for 2027 requirements."
  },
  "solar-and-affordable-housing": {
    "title": "Why Solar Matters for the Future of Affordable Housing",
    "dek": "For local authorities and housing associations delivering affordable developments, the expectations are rising just as build costs, regulation and financing requirements tighten.",
    "category": "Social housing",
    "author": "Danielle Todd",
    "date": "February 17, 2026",
    "truncated": false,
    "metaDescription": "For local authorities and housing associations delivering affordable developments, the expectations are rising just as build costs, regulation and financing requirements tighten."
  },
  "breaking-the-green-premium": {
    "title": "Breaking the Green Premium: Why It’s Holding Back Affordable, Competitive Homes",
    "dek": "Energy efficiency and renewable features are fast becoming must-haves in new homes. They cut bills, improve sustainability, and boost a property’s long-term value. But the",
    "category": "Home Design",
    "author": "Danielle Todd",
    "date": "November 6, 2025",
    "truncated": false,
    "metaDescription": null
  },
  "rising-energy-demand-bigger-systems": {
    "title": "Rising Energy Demand: Why New-Build Homes Need Bigger Solar Systems",
    "dek": "EVs, heat pumps and connected devices are driving record demand for electricity, yet most new-builds still get tiny solar systems that barely make a dent. To future-proof homes and protect residents from rising bills, solar needs to be sized for what’s coming — not what’s already outdated.",
    "category": "Home Design",
    "author": "Hugo Radford",
    "date": "September 19, 2025",
    "truncated": false,
    "metaDescription": "EVs, heat pumps and connected devices are driving record demand for electricity, yet most new-builds still get tiny solar systems that barely make a dent. To future-proof homes and protect residents from rising bills, solar needs to be sized for what’s coming — not what’s already outdated."
  },
  "best-roof-types-for-solar": {
    "title": "Best Roof Types for Solar Panels: A Guide for UK Housebuilders",
    "dek": "With rooftop solar about to become mandatory, solar-ready roofs are a must. This guide breaks down roof types, design tips, and system choices to help you integrate solar effectively into your developments.",
    "category": "Home Design",
    "author": "Scott Whiteside",
    "date": "August 6, 2025",
    "truncated": false,
    "metaDescription": "With rooftop solar about to become mandatory, solar-ready roofs are a must. This guide breaks down roof types, design tips, and system choices to help you integrate solar effectively into your developments."
  },
  "integrating-solar-and-heat-pumps": {
    "title": "Integrating Solar and Heat Pumps in New Builds: A Guide for Housebuilders",
    "dek": "As heat pumps replace gas, solar is the perfect partner. This guide explores how pairing ASHPs with smart solar systems can cut energy costs, manage SAP performance, and boost home efficiency.",
    "category": "Solar",
    "author": "Scott Whiteside",
    "date": "July 30, 2025",
    "truncated": false,
    "metaDescription": "As heat pumps replace gas, solar is the perfect partner. This guide explores how pairing ASHPs with smart solar systems can cut energy costs, manage SAP performance, and boost home efficiency."
  },
  "how-solar-helps-meet-epc-targets": {
    "title": "How Solar Helps Housebuilders Meet EPC Targets",
    "dek": "The UK housing market has never been more focused on energy efficiency. Buyers increasingly want homes with lower running costs and greater energy independence. Lenders",
    "category": "EPC",
    "author": "Danielle Todd",
    "date": "July 23, 2025",
    "truncated": true,
    "metaDescription": null
  },
  "what-is-gryd": {
    "title": "What Is Gryd? The Solar Subscription Changing How New Homes Are Powered in the UK",
    "dek": "The homes of tomorrow start with solar today. Learn how Gryd’s solar subscription model is making clean energy simple, accessible, and seamlessly built into new homes – no upfront cost, no added complexity.",
    "category": "Solar",
    "author": "Scott Whiteside",
    "date": "July 16, 2025",
    "truncated": false,
    "metaDescription": "The homes of tomorrow start with solar today. Learn how Gryd’s solar subscription model is making clean energy simple, accessible, and seamlessly built into new homes - no upfront cost, no added complexity."
  },
  "solar-maintenance-and-replacement-costs": {
    "title": "Solar Panel Maintenance and Replacement Costs: What Builders and Buyers Should Know",
    "dek": "What’s the real cost of solar ownership? This guide breaks down UK solar panel maintenance and replacement costs – and compares leasing vs ownership to help builders and buyers plan for the long term.",
    "category": "Maintenance",
    "author": "Danielle Todd",
    "date": "July 9, 2025",
    "truncated": false,
    "metaDescription": "What’s the real cost of solar ownership? This guide breaks down UK solar panel maintenance and replacement costs - and compares leasing vs ownership to help builders and buyers plan for the long term."
  },
  "do-you-need-a-solar-battery": {
    "title": "Do You Need a Solar Battery? Benefits for New Build Homes",
    "dek": "Rooftop solar is becoming mandatory – so what’s next? Discover how home batteries unlock energy independence, bigger savings, and long-term resilience – and how Gryd makes it simple, with no upfront cost.",
    "category": "Batteries",
    "author": "Hugo Radford",
    "date": "July 2, 2025",
    "truncated": false,
    "metaDescription": "Rooftop solar is becoming mandatory - so what’s next? Discover how home batteries unlock energy independence, bigger savings, and long-term resilience - and how Gryd makes it simple, with no upfront cost."
  },
  "battery-storage-and-grid-constraints": {
    "title": "How Onsite Battery Storage Can Solve Grid Constraints and Improve Project Viability",
    "dek": "Facing grid constraints on your new build projects? Learn how on-site solar and batteries can cut connection costs, boost viability, and meet low-carbon planning goals – without waiting on grid upgrades.",
    "category": "Batteries",
    "author": "Scott Whiteside",
    "date": "June 25, 2025",
    "truncated": false,
    "metaDescription": "Facing grid constraints on your new build projects? Learn how on-site solar and batteries can cut connection costs, boost viability, and meet low-carbon planning goals - without waiting on grid upgrades."
  },
  "solar-providers-compared": {
    "title": "Solar Providers Compared: Gryd vs Zero Bills vs SNRG",
    "dek": "Navigating solar options for new builds? This guide compares Gryd, Zero Bills, and microgrid solutions like SNRG – breaking down costs, ownership models, and resale impact – to help you choose the right fit for your project and buyers.",
    "category": "Energy",
    "author": "Scott Whiteside",
    "date": "June 18, 2025",
    "truncated": false,
    "metaDescription": "Navigating solar options for new builds? This guide compares Gryd, Zero Bills, and microgrid solutions like SNRG - breaking down costs, ownership models, and resale impact - to help you choose the right fit for your project and buyers."
  },
  "a-simple-guide-to-solar-leases": {
    "title": "A Simple Guide to Solar Leases: How They Work and Why They’re Growing",
    "dek": "A new solar model is changing the game. Learn how Gryd’s modern solar lease makes it easy to future-proof homes, cut carbon, and fight fuel poverty – without upfront costs or maintenance hassle.",
    "category": "Solar Leases",
    "author": "Danielle Todd",
    "date": "June 11, 2025",
    "truncated": false,
    "metaDescription": "A new solar model is changing the game. Learn how Gryd’s modern solar lease makes it easy to future-proof homes, cut carbon, and fight fuel poverty - without upfront costs or maintenance hassle."
  },
  "mandatory-solar-panels-in-new-homes": {
    "title": "Mandatory Solar Panels in New Homes: What Housebuilders Need to Know About the 2027 Solar Requirement",
    "dek": "Mandatory solar is coming by 2027. With the Future Homes Standard on the horizon, learn how fully funded solar solutions can help you stay compliant, meet buyer demand, and boost project viability – without the upfront cost.",
    "category": "Regulation",
    "author": "Scott Whiteside",
    "date": "June 4, 2025",
    "truncated": false,
    "metaDescription": "Mandatory solar is coming by 2027. With the Future Homes Standard on the horizon, learn how fully funded solar solutions can help you stay compliant, meet buyer demand, and boost project viability - without the upfront cost."
  },
  "project:lower-farm-mews": {
    "title": "How Gryd helped deliver higher sustainability, without adding a penny to the build cost",
    "dek": "Gryd delivered ~£100,000 of zero cost solar and battery systems to a 9-home Norfolk development, upgrading every home from ~20% to ~70% energy coverage. With no added build cost, all properties achieved EPC A ratings and offer buyers estimated lifetime savings of £30,000–£40,000.",
    "category": null,
    "author": "Scott Whiteside",
    "date": "April 28, 2026",
    "truncated": false,
    "metaDescription": "Gryd delivered £100k of solar and battery systems to a 9-home Norfolk development at zero cost to the developer. EPC A ratings and up to 70% energy coverage."
  },
  "project:st-ives-year-of-data": {
    "title": "Funded Solar and Battery for Three New Build Homes in St. Ives, Cornwall: A year with a Gryd solar subscription",
    "dek": "Gryd funded a solar and battery system at zero cost for BK Developments’ all-electric barn conversion in St. Ives, Cornwall. Twelve months of real data confirmed the result: EPC A ratings, 49% grid independence, and 14.1% lower energy bills for tenants.",
    "category": null,
    "author": "Scott Whiteside",
    "date": "April 26, 2026",
    "truncated": false,
    "metaDescription": "See how Gryd delivered funded solar for new build homes in St. Ives, Cornwall with BK Developments, cutting bills 15% and CO₂ 1.2t per home at zero cost."
  },
  "project:fifty-five-plot-analysis": {
    "title": "Independent Developer Analysis of Gryd on a 55-Home Site",
    "dek": "How one UK developer cut energy specification costs from £9,560 to £2,734 per plot on a 55-home site while keeping every home at EPC A. An independent analysis of Gryd’s funded solar and battery model versus self-supply, with full cost breakdowns and strategic findings.",
    "category": null,
    "author": "Scott Whiteside",
    "date": "April 21, 2026",
    "truncated": false,
    "metaDescription": "Independent analysis of a 55-home site shows Gryd's funded solar and battery model cuts developer costs by up to 71% while maintaining EPC A performance."
  }
};

export const authors: Record<string, Author> = {
  "Scott Whiteside": { name: "Scott Whiteside", initials: "SW" },
  "Danielle Todd": { name: "Danielle Todd", initials: "DT" },
  "Hugo Radford": { name: "Hugo Radford", initials: "HR" },
};
